default: &default
  adapter: postgresql
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["DB_DEV"] %>

test: &test
  <<: *default
  database: <%= ENV["DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DB_PRODUCTION"] %>